### ISSUE TITLE
page and out parameters : use string to define and retrieve generated PDF

### ISSUE THREAD

**Issue by ricardovf** [mreiferson/php-wkhtmltox#10]
Hi, first of all, congratulation on the great work!

First, i would like the out parameter when generating PDF:

"out The path of the output file, if "-" output is sent to stdout, if empty the output is stored in a buffer."

I would like the wkhtmltox_convert function to return a string with the generated PDF or to put it on a string that a i pass to wkhtmltox_convert, when i use the out parameter as '' or '-'

I also would like to use the page parameter to pass the HTML (page) as a string, as if i passed it via stdin.

"page The URL or path of the web page to convert, if "-" input is read from stdin."

Maybe send the header and footer HTML via php string would be very nice too!

Is it possible?

Thx a lot!

**Comment by mreiferson** [comment]
the out parameter isn't currently supported by libwkhtmltox, the library I'm using.

**Comment by ricardovf** [comment]
Hi!

With the current version of the lib is this possible already?

Thx!
