### ISSUE TITLE
Problems with PHP FastCGI - memory leak?

### ISSUE THREAD

**Issue by jnankin** [mreiferson/php-wkhtmltox#11]
Hello there, and thanks again for this great extension.

I started experiencing problems on my webserver shortly after installing phpwkhtmltox.  My server is running ubuntu 10.04, Apache2, with PHP FastCGI.  I had set PHP_FCGI_CHILDREN=10.  

After a short while my php-cgi processes started using 70mb+ of ram each.  Additionally, I started getting a lot of lines like this in my apache error log and my site basically shut down completely:
[Sat Mar 05 22:47:33 2011] [error] [client 67.184.53.79] FastCGI: comm with (dynamic) server "/var/local/fcgi/php-cgi-wrapper.fcgi" aborted: (first read) idle timeout (20 sec)
[Sat Mar 05 22:47:33 2011] [error] [client 67.184.53.79] FastCGI: incomplete headers (0 bytes) received from server "/var/local/fcgi/php-cgi-wrapper.fcgi"

As a result, I had to constantly restart the server to keep everything working.  I tried decreasing PHP_FCGI_CHILDREN, messing around with Apache MaxClients, and even turned off some services on my server to try to fix the problem.  The only thing I had done before the problem started was install the extension.  I turned the extension off in my php.ini and everything went back to normal.  

I don't really know what was ultimately causing the problem (and I do have the extension running successfully on another development machine), but I figured I should post in case others experience this type of behavior (and save them a couple of hours).

**Comment by mreiferson** [comment]
this issue is most likely due to the library itself and not the extension.  please see http://code.google.com/p/wkhtmltopdf/issues/list
