### ISSUE TITLE
Gtk-WARNING **: cannot open display

### ISSUE THREAD

**Issue by ventralnet** [mreiferson/php-wkhtmltox#12]
When you try to use the php extension to create a pdf (or image) of a site that uses flash, such as www.youtube.com you will receive an error message
Gtk-WARNING **: cannot open display:

Using the command line tool you can use xvfb-run to similate a graphical environment, but you can't do this workaround with the php extension.

Here is my modified test_pdf.php

<?php

foreach (range(1, 4) as $i) {
    wkhtmltox_convert('pdf',
        array('out' => '/tmp/test'.$i.'.pdf', 'imageQuality' => '95'), // global settings
        array(
            array('page' => 'http://www.youtube.com/')
            )); // object settings
}

?>

And here is the output

matt@ubuntu-server:~/Downloads$ sudo php test_pdf.php

(<unknown>:15111): Gtk-WARNING **: cannot open display:
matt@ubuntu-server:~/Downloads$

**Comment by mreiferson** [comment]
According to the wkhtmltopdf issue tracker flash seems unsupported, and flaky, in general.

http://code.google.com/p/wkhtmltopdf/issues/detail?id=48

**Comment by ventralnet** [comment]
Actually, in recent releases flash is supported.  The issue is it has to be run in an environment with a GUI display (with X running).  From the command line you can get it to work in a headless environment with the xvfb-run command which creates a new screen buffer.  Something like this

xvfb-run -a -s "-screen 0 1280x800x16" wkhtmltopdf www.youtube.com.

This of course probably isn't an issue in windows.  And isn't a viable work around when you are using the php

**Comment by ventralnet** [comment]
extension
