### ISSUE TITLE
configure: error: libwkhtmltox version 0.10 or later required

### ISSUE THREAD

**Issue by fbunadi** [mreiferson/php-wkhtmltox#14]
I'm using Mac OS10.6 and having trouble in configuring php-wkhtmltox
I've put the libwkhtmltopdf.\* (dylib file) in /usr/local/lib

84584 -rwxr-xr-x@ 1 root  wheel  43305948  1 Feb 07:04 libwkhtmltox.0.10.0.dylib
    8 lrwxrwxrwx@ 1 1000  1000         25  1 Feb 19:35 libwkhtmltox.0.10.dylib -> libwkhtmltox.0.10.0.dylib
    8 lrwxrwxrwx@ 1 1000  1000         25  1 Feb 19:35 libwkhtmltox.0.dylib -> libwkhtmltox.0.10.0.dylib
    8 lrwxrwxrwx@ 1 1000  1000         25  1 Feb 19:35 libwkhtmltox.dylib -> libwkhtmltox.0.10.0.dylib
    0 drwxr-xr-x  5 root  wheel       170 13 Jul 10:56 qt_menu.nib

I have also copied qt_menu.nib from the QT source to /usr/local/lib
I've put the wkhtmltox to /usr/local/include

And here's the content of my bash_profile:

export PATH=$PATH:/opt/local/bin:usr/local/bin:/usr/lib/pear/bin:/usr/local/include
export PATH
export MANPATH=$MANPATH:/opt/local/share/man
export INFOPATH=$INFOPATH:/opt/local/share/info
export DYLD_LIBRARY_PATH=/usr/local/lib

Below is the output when i tried to configure php-wkhtmltox
sudo ./configure
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /opt/local/bin/gsed
checking for cc... cc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... i386-apple-darwin10.7.4
checking host system type... i386-apple-darwin10.7.4
checking target system type... i386-apple-darwin10.7.4
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib
checking for PHP extension directory... /usr/lib/php/extensions/no-debug-non-zts-20090626
checking for PHP installed headers prefix... /usr/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.13.5 (ok)
checking for gawk... gawk
checking for libwkhtmltox support... yes, shared
found in /usr/local
checking for wkhtmltopdf_init in -lwkhtmltox... no
configure: error: libwkhtmltox version 0.10 or later required

I can do the command line wkhtmltopdf and wkhtmltoimage fine but I want to make this php binding to work so that I can call it on my php file instead of executing shell command through php

Do you have any resolution for this problem in Mac OS? Thanks

**Comment by fabio-phase** [comment]
I have the same issue on Mac OSX 10.7.1..

**Comment by mreiferson** [comment]
this is most likely due to downloading the libwkhtmltox OSX binaries which are only 32-bit and attempting to build a 64bit version of the extension.

if you look in config.log you'll probably see:

```
configure:4154: checking for wkhtmltopdf_init in -lwkhtmltox
configure:4189: cc -o conftest -g -O2   conftest.c -lwkhtmltox   >&5
ld: warning: in /usr/lib/libwkhtmltox.dylib, file was built for i386 which is not the architecture being linked (x86_64)
Undefined symbols:
  "_wkhtmltopdf_init", referenced from:
      _main in cc9b1jWu.o
ld: symbol(s) not found
collect2: ld returned 1 exit status
```

You'll need to build your own 64-bit libwkhtmltox in order to build 64bit extension on OSX.
