### ISSUE TITLE
size.pageSize is ignored

### ISSUE THREAD

**Issue by jsthind** [mreiferson/php-wkhtmltox#15]
Hello,

I am on Ubuntu 10.04 and using wkhtmltox 0.10.0_rc2 . Everything works perfectly except that size.pageSize is ignored and default size of A4 is used instead. I am using the below code:

<?php
wkhtmltox_convert('pdf',
        array('out' => 'tmp/test2.pdf', 'imageQuality' => '95', 'size.paperSize' => 'A9'), // global settings
        array(
            array('page' => 'http://www.google.com/')
        )); // object settings
?>

Please help.

Thanks,
Jatinder Thind

**Comment by jsthind** [comment]
Hi,

Can you please take a look. Would appreciate a response.

Thanks,
Jatinder Thind

**Comment by mreiferson** [comment]
@jsthind - just going through old issues and it looks like the problem here is the documentation is wrong for this variable - it's actually `size.pageSize`
