### ISSUE TITLE
Extension does not load

### ISSUE THREAD

**Issue by zavg** [mreiferson/php-wkhtmltox#16]
i686, Ubuntu
I have installed i386 libwkhtmltox and php-wkhtmltox exactly according your instructions, added appropriate line in php.ini, copied extension file to php standart extensions library, but the extension does not appear in phpinfo output...

**Comment by mreiferson** [comment]
hi zavg - can you enable verbose logging of startup for php and see if there is any error we can further diagnose?

**Comment by zavg** [comment]
Thank you very much for quick resoponce.
Ok. How should I do it?
I set
error_reporting = E_ALL & ~E_DEPRECATED
display_errors = On
display_startup_errors = On
and restarted apache2. Where I should search for errors logging?

**Comment by mreiferson** [comment]
I would try running php from the command line with `display_startup_errors = On`

**Comment by zavg** [comment]
Nothing, just regular output...
