### ISSUE TITLE
Problems installing it on Ubuntu

### ISSUE THREAD

**Issue by jnbdz** [mreiferson/php-wkhtmltox#17]
When I do ./configure I get this error:

checking for libwkhtmltox support... yes, shared
not found
configure: error: Please install libwkhtmltox

$PATH -> /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/lib:/include

This is what I have in /lib (They are other files and folders):

lrwxrwxrwx  1 root root      22 Nov 25 20:44 libwkhtmltox.so -> libwkhtmltox.so.0.10.0*
lrwxrwxrwx  1 root root      22 Nov 25 20:44 libwkhtmltox.so.0 -> libwkhtmltox.so.0.10.0*
lrwxrwxrwx  1 root root      22 Nov 25 20:44 libwkhtmltox.so.0.10 -> libwkhtmltox.so.0.10.0*
-rwxr-xr-x  1 root root  300072 Nov 25 20:44 libwkhtmltox.so.0.10.0*

So what could be causing this problem?

**Comment by jnbdz** [comment]
I was able to install it. But for some reason it does not work.

Here are the errors I get:

Apache2 log:
wkhtmltox: cannot connect to X server

$php test_image.php

Fatal error:  Call to undefined function wkhtmltox_convert() in /var/www/test_image.php

Thanks in advance for any help.

**Comment by jnbdz** [comment]
When I do this:

ldconfig -v | grep wkhtml

This is what I get:

/sbin/ldconfig.real: Can't stat /usr/lib32/mesa: No such file or directory
/sbin/ldconfig.real: Path `/lib/x86_64-linux-gnu' given more than once
/sbin/ldconfig.real: Path`/usr/lib/x86_64-linux-gnu' given more than once
    libwkhtmltox.so.0 -> libwkhtmltox.so
    libwkhtmltox.so.0 -> libwkhtmltox.so.0.10.0

**Comment by jnbdz** [comment]
I did some other test.

And if I do this in the terminal:

```
xvfb-run php test_*
```

It works. But if I call test_image.php via the browser I get an error.

It says:
    wkhtmltox: cannot connect to X server

**Comment by mreiferson** [comment]
@jnbdz - see http://code.google.com/p/wkhtmltopdf/issues/detail?id=3&can=1

this is an issue with the `libwkhtmltox` library, not the php module.
