### ISSUE TITLE
phpwkhtmltox install on UBUNTU

### ISSUE THREAD

**Issue by karolymarton** [mreiferson/php-wkhtmltox#2]
Hi!
I couldn't make it works until i copy the libwkhtmltox.so with another name libwkhtmltox.so.0
Heres my files list what worked: 
/usr/local/include/wkhtmltox
/usr/local/lib/libwkhtmltox.so
/usr/local/lib/libwkhtmltox.so.0

**Comment by karolymarton** [comment]
After that phpwkhtmltox extension will be load, but wont work yet.
i have installed the qt4 libs too, apt-get install libqt4-dev qt4-dev-tools
but when i look into error log it says: 
QPainter::begin(): Returned false

**Comment by karolymarton** [comment]
/usr/bin/wkhtmltopdf works but phpwkhtmltopdf not:/

**Comment by karolymarton** [comment]
Can somebody help me about the QPainter::begin(): Returned false message?

**Comment by mreiferson** [comment]
do you have write access to the directory where you're creating the pdf?

**Comment by karolymarton** [comment]
sry, that was a dumb fail... A granted the write right, and the PDF was appear in the right place.
Thank you:)
