### ISSUE TITLE
Headers and footers not working

### ISSUE THREAD

**Issue by BilboUK** [mreiferson/php-wkhtmltox#20]
Thanks for the excellent extension.  I'm having a problem getting headers and footers to work.  AFAIK I have a patched QT lib (libwkhtmltox-0.11.0_rc1-i386.tar.bz2 downloaded from the main site) and things like "imageQuality" work which seems to confirm this.

However none of the header or footer settings seem to do anything.  

E.g. 
   wkhtmltox_convert('pdf', 
        array('out' => '/tmp/test1.pdf', "margin.top" => 20, 'header.center' => 'Page Header' ), 
        array(array('page' => 'http://www.visionaryrenesis.com/')));

does not display the header text.  But using the static patched binary does work:
   wkhtmltopdf --margin-top 20 --header-center 'Page Header' 'http://www.visionaryrenesis.com/' '/tmp/test2.pdf'

Thanks for any help you can give me.

**Comment by mreiferson** [comment]
@BilboUK I'd have to check the source for `libwkhtmltox` but I'm pretty sure some options might not be fully implemented.

**Comment by BilboUK** [comment]
Ah my bad - the header & footer settings are pdf _object_ settings not pdf global settings
(c.f. http://www.cs.au.dk/~jakobt/libwkhtmltox_0.10.0_doc/pagesettings.html )

So all I need do is specify them like this:

wkhtmltox_convert( 'pdf',
    array(  'out' => '/tmp/test1.pdf', 'margin.top' => 20 ),
    array( array( 'page' => 'http://www.visionaryrenesis.com/', 'header.center' => 'Page Header' ) ));

Seems a bit odd that the header size (viz. margin.top) is global whilst the header.~ is local, but there we go.

Bit of a nuisance when pulling in multiple pages since you have to specify all the other object settings _each_ time but no biggie I suppose (and means you could have different headers on different 'page's if you want) :

``` php
wkhtmltox_convert('pdf',
  array( 'out' => '/tmp/test1.pdf', 'margin.top' => 20 ),
  array( array('page' => 'http://www.visionaryrenesis.com/', 'header.center' => 'Page Header' ),
         array('page' => 'http://www.google.com/', 'header.center' => 'Page Header' ) ));
```

Thanks again for this very useful php extension.

**Comment by mreiferson** [comment]
great, thanks!

closing...
