### ISSUE TITLE
Error opening with Acrobat Reader

### ISSUE THREAD

**Issue by eduardbulai** [mreiferson/php-wkhtmltox#26]
For those who are having problems opening the exported PDF with Acrobat Reader (message: There was an error opening this document. The root object is missing or invalid) - the problem is not related to the php extension but with wkhtmltopdf. I posted a quick & dirty fix on the wkhtmltopdf Google Code page. You can find it here: http://code.google.com/p/wkhtmltopdf/issues/detail?id=463#c9

I hope this helps.

**Comment by mreiferson** [comment]
thanks for the tip @eduardbulai, gonna close this
