### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by karolymarton** [mreiferson/php-wkhtmltox#3]
Hi!

Anybody can set disable-smart-shrinking?
I have few cli arguments, but i can't find a documentation how can it be passed to wkhtmltopdf via phpwkhtmltox...
wkhtmltopdf/src/lib/pdfsettings.cc contains some configuration, but not all...

**Comment by mreiferson** [comment]
you can see all of the options available here:

http://www.cs.au.dk/~jakobt/libwkhtmltox_0.10.0_doc/pagesettings.html

**Comment by karolymarton** [comment]
Thank you again!:)
