### ISSUE TITLE
Multiple run test

### ISSUE THREAD

**Issue by karolymarton** [mreiferson/php-wkhtmltox#4]
Dear MReiferson!

When i run your script in a for statement, i got wrong pdfs. (Except the first, what is okey)
    for ($i = 0; $i < 5; $i++){
    wkhtmltox_convert('pdf',
        array('out' => dirname(**FILE**).'/test_'.$i.'.pdf', 'imageQuality' => '95'), // global settings
            array(
                    array('page' => 'http://www.visionaryrenesis.com/'),
                    array('page' => 'http://www.google.com/')
            )
        ); // object settings
    }

RESULT:
test_0.pdf              07-Oct-2010 12:34   45K  
test_1.pdf              07-Oct-2010 12:34   25K  
test_2.pdf              07-Oct-2010 12:34   25K  
test_3.pdf              07-Oct-2010 12:34   25K  
test_4.pdf              07-Oct-2010 12:34   25K  

http://martondesign.com/temp/wkhtmltopdf/test_0.pdf (good)
http://martondesign.com/temp/wkhtmltopdf/test_1.pdf (wrong)

It processes the HTML, but not CSS, and images.

**Comment by karolymarton** [comment]
If i run the script without for, but started by hand multiple times, i got the same result. If restart apache between the runs, i got good result. So there should be something with the memory handling... This issue doesn't turn out with cli version because there every wkhtml2pdf instance closing after run.

**Comment by mreiferson** [comment]
See if you can find anything in your server's logs, phps logs, etc... theres got to be some sort of error output somewhere that I can debug.

**Comment by karolymarton** [comment]
Nothing in the error logs:/ It seems okey, but the result not.
Can you reproduce this issue on your instance?

**Comment by karolymarton** [comment]
If comment out these 2 rows, it works great!
        //wkhtmltopdf_destroy_converter(c);
        //wkhtmltopdf_deinit();

**Comment by mreiferson** [comment]
you shouldn't comment out destroy_converter - I'm going to play around with deinit()... there may need to be some API changes as a result of this.

Thanks.

**Comment by karolymarton** [comment]
I just have short time to debug, so i commented both before i must leave on friday:)
I will read today some source and api about these 2 function... i hope i can help about it..

**Comment by mreiferson** [comment]
hi - i've corrected this issue...

please pull, build, and try again

**Comment by karolymarton** [comment]
Hi!
I tried it again, everything went fine!:)
Thanks for the patch!
