### ISSUE TITLE
checking for wkhtmltopdf_init in -lwkhtmltox... no (CentOS 5)

### ISSUE THREAD

**Issue by mreiferson** [mreiferson/php-wkhtmltox#5]
"I'm getting an error when trying to configure it. I'm on Cent OS 5, I've got libwkhtmltox.so (version 10.0) in /usr/local/lib and that path is in $LD_LIBRARY_PATH, and i've got the folder wkhtmltox and its contents in /usr/local/include, which is in my $PATH. I've also got wkhtmltox in /usr/local/bin, which means I can run it through the command line no problems. when I run ./configure, it finds the library, and then on the next line looks for "wkhtmltopdf_init in -lwkhtmltox... no", then tells me I need libwkhtmltox version 0.10 or later."

**Comment by mreiferson** [comment]
the important thing to note here is compiling the extension for the right architecture you want with the correct libwkhtmltox architecture.

ie - 64bit centos, 64bit php, 64bit libwkhtmltox, 64bit php-wkhtmltox

Note: wkhtmltopdf does not publish binary distributions for 64bit linux so if this is the setup you're having trouble with you'll have to build libwkhtmltox for a 64bit architecture in CentOS 64.

**Comment by jsthind** [comment]
I am also getting the same error - "configure: error: libwkhtmltox version 0.10 or later required"

I am on Centos5.5 32 bit. The libwkhtmltox.so file is at /usr/lib/

The "wkhtmltox" folder is at /usr/local/include/

Please help.

**Comment by mreiferson** [comment]
@jsthind

in your case it should be as simple as putting the lib files in /usr/local/include, the same parent path as you have your include files.

let me know if that works.

**Comment by jsthind** [comment]
I copied the libwkhtmltox.so file from /usr/lib/ to /usr/local/include/ but still get the same error. To provide more details, the last four lines of the output are:

checking for libwkhtmltox support... yes, shared
found in /usr/local
checking for wkhtmltopdf_init in -lwkhtmltox... no
configure: error: libwkhtmltox version 0.10 or later required

**Comment by mreiferson** [comment]
i'm sorry - i meant put the lib files in /usr/local/lib

**Comment by jsthind** [comment]
Thank you for the response. I Copied libwkhtmltox.so to /usr/local/lib/ but still get the same error.

The various paths as displayed by ./configure command's output:

checking for PHP prefix... /usr/local
checking for PHP includes... -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/lib/php/extensions/no-debug-non-zts-20090626
checking for PHP installed headers prefix... /usr/local/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.13.5 (ok)
checking for gawk... gawk
checking for libwkhtmltox support... yes, shared
found in /usr/local
checking for wkhtmltopdf_init in -lwkhtmltox... no
configure: error: libwkhtmltox version 0.10 or later required

Maybe the above will shed some light on the error.

**Comment by mreiferson** [comment]
try running:

ldconfig

and then configure again

**Comment by jsthind** [comment]
I had to recompile my own version of QT to get the extension to configure and compile. Now the extension is compiled and installed on my Centos.

But when I try to generate PDF, all images are missing. Any help with this?

**Comment by jsthind** [comment]
To add more details to above: 

I managed to configure/compile php-wkhtmltox by compiling my own version of QT. However there is a slight problem.

When I run the  "php test_pdf.php", I get the PDF just fine. But when I call the same file through browser, the generated PDF has some of the images missing.

To be precise, only PNG images are included. GIF and JPG images are left out.

Please help me with this.

**Comment by mreiferson** [comment]
You're probably missing the libjpg dependency during compilation of QT or libwkhtmltox...

**Comment by jalder** [comment]
After combing through the config log, I found that it was complaining about "undefined reference to `FcFreeTypeQueryFace'", essentially you need to upgrade to fontconfig-2.4.2 as that API call wasn't present on the version that comes with CentOS.

Fix:

Build fontconfig-2.4.2 from source and install http://www.linuxfromscratch.org/blfs/view/6.3/general/fontconfig.html

Then install php-wkhtmltox

http://www.stormfrontproductions.net

**Comment by mreiferson** [comment]
@jalder - thanks!

I must have upgraded that package...

going to close this...

**Comment by szaronsj** [comment]
I tried to install fontconfig and to install the various x11 font packages, but I am still getting blank boxes instead of characters.  Can anyone assist with this?

**Comment by mreiferson** [comment]
@szaronsj - bases on your emails I think the issue you're running into is that you need to build the 64-bit libwkhtmltox libs manually.  The amd64 binary distribution won't work.

**Comment by szaronsj** [comment]
Thanks. How do I go about doing that? (Sorry for the newbie question)

I found out how to do it for wkhtmltopdf here: http://code.google.com/p/wkhtmltopdf/wiki/compilation
But I cannot find the QT libraries for libwkhtmltox

**Comment by szaronsj** [comment]
Nevermind... figured it out.  I had the correct architecture installed, but needed to install urw fonts.

$ yum install urw-fonts
