### ISSUE TITLE
./configure: line 3370: !DOCTYPE: No such file or directory 

### ISSUE THREAD

**Issue by macdabby** [mreiferson/php-wkhtmltox#6]
CENTOS 5.5 i686

I put the wkhtmltox files in the places described in the instructions
downloaded the files from this site

did phpize with no problems
./configure gives me this error:

./configure: line 3370: !DOCTYPE: No such file or directory
./configure: line 3371: syntax error near unexpected token `newline'
./configure: line 3371:`  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">'

**Comment by mreiferson** [comment]
something must have gone terribly wrong with phpize - it's basically saying your configure script is broken...
