### ISSUE TITLE
Stdout / write pdf to page

### ISSUE THREAD

**Issue by jnankin** [mreiferson/php-wkhtmltox#7]
Is there a way to write a pdf directly to php's output stream?  That way you could just change the header's content type and be able to have the user view the pdf directly without pointing them to a file on the server?

I tried specifying "-" for "out" but that didn't work.  I'd rather not create a bunch of files in my tmp directory that have to be purged after a few hours.

**Comment by mreiferson** [comment]
i probably need to specifically handle this case in the extension - I'll take a look...

**Comment by jnankin** [comment]
Any ideas about possible solutions/patches?

**Comment by mreiferson** [comment]
i haven't had a chance implement these changes yet - it will need to be explicitly handled.

**Comment by jnankin** [comment]
Ok, wasn't trying to be pushy.  Thanks again, looking forward, and great work!

**Comment by triptec** [comment]
I'm just writing to /tmp and then a file_get_contents() but yeah I would be nice to get the data strait away..

**Comment by char101** [comment]
You can also write the output to tmpfs.

**Comment by mreiferson** [comment]
@jnankin,

I tested '-' on the command line and it works fine - is it not working when used within a webserver?

have you tried:

```
ob_start();
//convert here, with '-'
echo ob_get_clean();
```

**Comment by jnankin** [comment]
Correct, my code also works on the command line.  Same code on my webserver does not work.  Looks like I'm getting "QPainter::begin(): Returned false" in the logs.

However, I can use wkhtmltox via webserver/php to write a pdf to a properly permissioned directory - that does work.  It's just giving me trouble with writing to the output stream.

**Comment by mreiferson** [comment]
That error message usual implies that it can't write to "file", in this case stdout.  Because it works on the command line im more convinced that this is some issue with apache/mod_php.

Going to do some more investigating, thanks.

**Comment by char101** [comment]
Below code works for me (php 5.3.4, win32, apache2)

<pre>
&lt;?php

$p = proc_open('G:\\tools\\wkhtmltok\\wkhtmltopdf.exe - -', array(
    array('pipe', 'r'), 
    array('pipe', 'w'),
    array('pipe', 'w')
), $pipes);
fwrite($pipes[0], '&lt;p&gt;hello&lt;/p&gt;');
fclose($pipes[0]);

file_put_contents('result.pdf', stream_get_contents($pipes[1]));
fclose($pipes[1]);

echo stream_get_contents($pipes[2]);
fclose($pipes[2]);

proc_close($p);
</pre>

**Comment by mreiferson** [comment]
as a follow up - libwkhtmltox doesn't currently support the - option for stdout
