### ISSUE TITLE
Crop setting not working

### ISSUE THREAD

**Issue by dinozauras** [mreiferson/php-wkhtmltox#8]
wkhtmltox_convert('image', array('out' => 'test.jpg',  'crop-h' => 500,  'in' => 'someurl'));

It works fine with  setting such as `quality => 50`. But when I try to set cropping, the setting is just ignored. Tried several ways: crop-height, crop.height, height. Even a 2D array, but it gave me an error. How should it be set correctly? 

Thank you in advance.

**Comment by mreiferson** [comment]
Hi - doesn't look like thats the correct name for that setting... see

http://www.cs.au.dk/~jakobt/libwkhtmltox_0.10.0_doc/pagesettings.html#pagePdfGlobal

It looks like you might be talking about 'crop.height'

**Comment by dinozauras** [comment]
I've tried 'crop.height'. Nevermind, ended up using wkhtmltox via exec().

**Comment by szaronsj** [comment]
Was there ever a resolution on how to get crop for images working within php-wkhtmltox?  Is there a different syntax that we're missing as I'm having the same issues.  Crop does not seem to function at all, though quality and screenWidth do seem to work.

**Comment by mreiferson** [comment]
I dont think crop was implemented in libwkhtlmtox, unfortunately.
