### ISSUE TITLE
Can't load extension

### ISSUE THREAD

**Issue by mouloud** [mreiferson/php-wkhtmltox#9]
Hi there,
i'm not very experimented on unix, but I tried to install this php bindings, and it don't work.
I first installed wkhtmltopdf (static) and it works fine on command line.
Then I downloaded libwkhtmltox (static), and copied lib/libwkhtmltox.so to /usr/local/lib.
I copied also the include/wkhtmltox directory into /usr/local/include
Then, I dowloaded this binding, and ran phpize, configure and make install, without error.
I added "extension=phpwkhtmltox.so" in my php.ini and restarted apache2.
I get this error :
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20060613+lfs/phpwkhtmltox.so' - libwkhtmltox.so.0: cannot open shared object file: No such file or directory in Unknown on line 0

I checked /usr/lib/php5/20060613+lfs/, and phpwkhtmltox.so is there. So I suppose it's a dependency problem. What did I missed ?

Thanks

**Comment by mreiferson** [comment]
Can you paste the output when you phpize's configured and installed the extension?

**Comment by mouloud** [comment]
<pre><code>bruneprd:~/wkhtmltopdf/mreiferson-php-wkhtmltox-e6b14a0# phpize
Configuring for:
PHP Api Version:         20041225
Zend Module Api No:      20060613
Zend Extension Api No:   220060519
bruneprd:~/wkhtmltopdf/mreiferson-php-wkhtmltox-e6b14a0# ./configure
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr
checking for PHP includes... -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
checking for PHP extension directory... /usr/lib/php5/20060613+lfs
checking for PHP installed headers prefix... /usr/include/php5
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... invalid
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking for libwkhtmltox support... yes, shared
found in /usr/local
checking for wkhtmltopdf_init in -lwkhtmltox... yes
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking for g77... no
checking for xlf... no
checking for f77... no
checking for frt... no
checking for pgf77... no
checking for cf77... no
checking for fort77... no
checking for fl32... no
checking for af77... no
checking for xlf90... no
checking for f90... no
checking for pgf90... no
checking for pghpf... no
checking for epcf90... no
checking for gfortran... no
checking for g95... no
checking for xlf95... no
checking for f95... no
checking for fort... no
checking for ifort... no
checking for ifc... no
checking for efc... no
checking for pgf95... no
checking for lf95... no
checking for ftn... no
checking whether we are using the GNU Fortran 77 compiler... no
checking whether  accepts -g... no
checking the maximum length of command line arguments... 98304
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/ld -m elf_i386) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
configure: creating libtool
appending configuration tag "CXX" to libtool
appending configuration tag "F77" to libtool
configure: creating ./config.status
config.status: creating config.h
bruneprd:~/wkhtmltopdf/mreiferson-php-wkhtmltox-e6b14a0# make install
/bin/sh /root/wkhtmltopdf/mreiferson-php-wkhtmltox-e6b14a0/libtool --mode=compile cc  -I. -I/root/wkhtmltopdf/mreiferson-php-wkhtmltox-e6b14a0 -DPHP_ATOM_INC -I/root/wkhtmltopdf/mreiferson-php-wkhtmltox-e6b14a0/include -I/root/wkhtmltopdf/mreiferson-php-wkhtmltox-e6b14a0/main -I/root/wkhtmltopdf/mreiferson-php-wkhtmltox-e6b14a0 -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/local/include  -DHAVE_CONFIG_H  -g -O2   -c /root/wkhtmltopdf/mreiferson-php-wkhtmltox-e6b14a0/phpwkhtmltox.c -o phpwkhtmltox.lo 
mkdir .libs
 cc -I. -I/root/wkhtmltopdf/mreiferson-php-wkhtmltox-e6b14a0 -DPHP_ATOM_INC -I/root/wkhtmltopdf/mreiferson-php-wkhtmltox-e6b14a0/include -I/root/wkhtmltopdf/mreiferson-php-wkhtmltox-e6b14a0/main -I/root/wkhtmltopdf/mreiferson-php-wkhtmltox-e6b14a0 -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/local/include -DHAVE_CONFIG_H -g -O2 -c /root/wkhtmltopdf/mreiferson-php-wkhtmltox-e6b14a0/phpwkhtmltox.c  -fPIC -DPIC -o .libs/phpwkhtmltox.o
/bin/sh /root/wkhtmltopdf/mreiferson-php-wkhtmltox-e6b14a0/libtool --mode=link cc -DPHP_ATOM_INC -I/root/wkhtmltopdf/mreiferson-php-wkhtmltox-e6b14a0/include -I/root/wkhtmltopdf/mreiferson-php-wkhtmltox-e6b14a0/main -I/root/wkhtmltopdf/mreiferson-php-wkhtmltox-e6b14a0 -I/usr/include/php5 -I/usr/include/php5/main -I/usr/include/php5/TSRM -I/usr/include/php5/Zend -I/usr/include/php5/ext -I/usr/include/php5/ext/date/lib -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -I/usr/local/include  -DHAVE_CONFIG_H  -g -O2   -o phpwkhtmltox.la -export-dynamic -avoid-version -prefer-pic -module -rpath /root/wkhtmltopdf/mreiferson-php-wkhtmltox-e6b14a0/modules  phpwkhtmltox.lo -Wl,-rpath,/usr/local/lib -L/usr/local/lib -lwkhtmltox
cc -shared  .libs/phpwkhtmltox.o  -L/usr/local/lib -lwkhtmltox  -Wl,-rpath -Wl,/usr/local/lib -Wl,-soname -Wl,phpwkhtmltox.so -o .libs/phpwkhtmltox.so
creating phpwkhtmltox.la
(cd .libs && rm -f phpwkhtmltox.la && ln -s ../phpwkhtmltox.la phpwkhtmltox.la)
/bin/sh /root/wkhtmltopdf/mreiferson-php-wkhtmltox-e6b14a0/libtool --mode=install cp ./phpwkhtmltox.la /root/wkhtmltopdf/mreiferson-php-wkhtmltox-e6b14a0/modules
cp ./.libs/phpwkhtmltox.so /root/wkhtmltopdf/mreiferson-php-wkhtmltox-e6b14a0/modules/phpwkhtmltox.so
cp ./.libs/phpwkhtmltox.lai /root/wkhtmltopdf/mreiferson-php-wkhtmltox-e6b14a0/modules/phpwkhtmltox.la
PATH="$PATH:/sbin" ldconfig -n /root/wkhtmltopdf/mreiferson-php-wkhtmltox-e6b14a0/modules
----------------------------------------------------------------------
Libraries have been installed in:
   /root/wkhtmltopdf/mreiferson-php-wkhtmltox-e6b14a0/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the `LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the `LD_RUN_PATH' environment variable
     during linking
   - use the `-Wl,--rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to `/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
Installing shared extensions:     /usr/lib/php5/20060613+lfs/
</code></pre>

**Comment by mreiferson** [comment]
try running:

$ ldconfig
$ ldd /usr/lib/php5/20060613+lfs/phpwkhtmltox.so

and paste the output

**Comment by mouloud** [comment]
<pre><code>
bruneprd:~# ldconfig
bruneprd:~# ldd /usr/lib/php5/20060613+lfs/phpwkhtmltox.so
    linux-gate.so.1 =>  (0xffffe000)
    libwkhtmltox.so.0 => /usr/local/lib/libwkhtmltox.so.0 (0x55576000)
    libc.so.6 => /lib/libc.so.6 (0x57754000)
    libXrender.so.1 => /usr/lib/libXrender.so.1 (0x57893000)
    libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x5789c000)
    libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x578c7000)
    libz.so.1 => /usr/lib/libz.so.1 (0x5793c000)
    libXext.so.6 => /usr/lib/libXext.so.6 (0x57951000)
    libX11.so.6 => /usr/lib/libX11.so.6 (0x5795f000)
    libdl.so.2 => /lib/libdl.so.2 (0x57a4f000)
    librt.so.1 => /lib/librt.so.1 (0x57a53000)
    libpthread.so.0 => /lib/libpthread.so.0 (0x57a5c000)
    libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x57a74000)
    libm.so.6 => /lib/libm.so.6 (0x57b62000)
    libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x57b88000)
    /lib/ld-linux.so.2 (0x55555000)
    libexpat.so.1 => /usr/lib/libexpat.so.1 (0x57b96000)
    libXau.so.6 => /usr/lib/libXau.so.6 (0x57bbc000)
    libxcb-xlib.so.0 => /usr/lib/libxcb-xlib.so.0 (0x57bbf000)
    libxcb.so.1 => /usr/lib/libxcb.so.1 (0x57bc1000)
    libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x57bd9000)

</code></pre>

Thanks for your time !

**Comment by tomconvac** [comment]
Same here.

I'm getting exactly the same message. I even tried to recompile extension after noticing that I'm missing qt4 and qt4-devel but no luck - it still doesn't work.

I'm on PHP 5.2.6.

**Comment by mreiferson** [comment]
What architecture are you running for PHP (64 or 32 bit)?  If you're running 64-bit you may need to compile your own library for libwkhtmltox as the downloads antialize provides are only 32-bit for linux.

**Comment by tomconvac** [comment]
I am running on i386 Fedora 8.

**Comment by mreiferson** [comment]
does wkhtmltopdf work on the command line for you?

some people have had issues with fontconfig not being installed on a system.

can you paste the output of:

ldd /usr/local/lib/libwkhtmltox.so.0

**Comment by mouloud** [comment]
Don't know if you was asking to me, but yes, command line work for me, I use it every day, and this is great !! My PHP is 32 bit, and this is the ldd you asked for :

bruneprd:~# ldd /usr/local/lib/libwkhtmltox.so.0
    linux-gate.so.1 =>  (0xffffe000)
    libXrender.so.1 => /usr/lib/libXrender.so.1 (0x57751000)
    libfontconfig.so.1 => /usr/lib/libfontconfig.so.1 (0x5775a000)
    libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x57786000)
    libz.so.1 => /usr/lib/libz.so.1 (0x577fb000)
    libXext.so.6 => /usr/lib/libXext.so.6 (0x57810000)
    libX11.so.6 => /usr/lib/libX11.so.6 (0x5781e000)
    libdl.so.2 => /lib/libdl.so.2 (0x5790d000)
    librt.so.1 => /lib/librt.so.1 (0x57911000)
    libpthread.so.0 => /lib/libpthread.so.0 (0x5791b000)
    libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x57933000)
    libm.so.6 => /lib/libm.so.6 (0x57a21000)
    libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x57a47000)
    libc.so.6 => /lib/libc.so.6 (0x57a54000)
    libexpat.so.1 => /usr/lib/libexpat.so.1 (0x57b92000)
    libXau.so.6 => /usr/lib/libXau.so.6 (0x57bb9000)
    libxcb-xlib.so.0 => /usr/lib/libxcb-xlib.so.0 (0x57bbc000)
    libxcb.so.1 => /usr/lib/libxcb.so.1 (0x57bbe000)
    /lib/ld-linux.so.2 (0x55555000)
    libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x57bd6000)
